# instana registry
INSTANA_REGISTRY_CHART_VERSION=1.0.0

# instana operator
INSTANA_OPERATOR_CHART_VERSION=1.6.0

# core
INSTANA_CORE_CHART_VERSION=1.14.0

# unit
INSTANA_UNIT_CHART_VERSION=1.2.0

# cert-manager
CERT_MANAGER_VERSION=v1.18.2

# kafka
KAFKA_OPERATOR_CHART_VERSION=0.47.0
KAFKA_INSTANCE_CHART_VERSION=1.6.0

# elasticsearch
ES_OPERATOR_CHART_VERSION=3.0.0
ES_INSTANCE_CHART_VERSION=1.3.0

# postgres
POSTGRES_OPERATOR_CHART_VERSION=0.24.0
POSTGRES_INSTANCE_CHART_VERSION=1.5.0

# cassandra
CASSANDRA_OPERATOR_CHART_VERSION=0.60.0
CASSANDRA_OPERATOR_SYSTEMLOGGER_IMAGE_TAG=1.26.0_v0.17.0
CASSANDRA_OPERATOR_K8SSANDRACLIENT_IMAGE_TAG=0.8.3_v0.25.0
CASSANDRA_INSTANCE_CHART_VERSION=1.6.0

# clickhouse
CLICKHOUSE_OPERATOR_CHART_VERSION=v1.2.0
CLICKHOUSE_INSTANCE_CHART_VERSION=1.10.0

# beeinstana
BEEINSTANA_OPERATOR_CHART_VERSION=1.96.0
BEEINSTANA_INSTANCE_CHART_VERSION=1.3.0
