# instana registry
INSTANA_REGISTRY_CHART_VERSION=1.0.0

# instana operator
INSTANA_OPERATOR_CHART_VERSION=1.2.0
INSTANA_OPERATOR_IMAGE_TAG=1.2.0

# core
INSTANA_CORE_CHART_VERSION=1.2.0

# unit
INSTANA_UNIT_CHART_VERSION=1.0.0

# cert-manager
CERT_MANAGER_VERSION=v1.16.2

# kafka
KAFKA_OPERATOR_CHART_VERSION=0.42.0
KAFKA_OPERATOR_IMAGE_TAG=0.42.0_v0.12.0
KAFKA_INSTANCE_CHART_VERSION=1.0.0

# elasticsearch
ES_OPERATOR_CHART_VERSION=2.14.0
ES_OPERATOR_IMAGE_TAG=2.14.0_v0.14.0
ES_INSTANCE_CHART_VERSION=1.0.0

# postgres
POSTGRES_OPERATOR_CHART_VERSION=0.21.1
POSTGRES_OPERATOR_IMAGE_TAG=v1.21.1_v0.8.0
POSTGRES_INSTANCE_CHART_VERSION=1.0.0

# cassandra
CASSANDRA_OPERATOR_CHART_VERSION=0.53.6
CASSANDRA_OPERATOR_IMAGE_TAG=1.22.4_v0.17.0
CASSANDRA_OPERATOR_APPVERSION=1.18.2
CASSANDRA_OPERATOR_SYSTEMLOGGER_IMAGE_TAG=1.22.4_v0.6.0
CASSANDRA_OPERATOR_K8SSANDRACLIENT_IMAGE_TAG=0.6.0_v0.7.0
CASSANDRA_INSTANCE_CHART_VERSION=1.0.0

# clickhouse
CLICKHOUSE_OPERATOR_CHART_VERSION=v1.2.0
CLICKHOUSE_OPERATOR_IMAGE_TAG=v1.2.0
CLICKHOUSE_INSTANCE_CHART_VERSION=1.1.0

# beeinstana
BEEINSTANA_OPERATOR_CHART_VERSION=1.63.0
BEEINSTANA_OPERATOR_IMAGE_TAG=v1.63.0
BEEINSTANA_INSTANCE_CHART_VERSION=1.0.0
